---
- name: Import hc_ovmf_template vms
  hosts: all
  vars:
    - image_name:
      - vtpm-other-nosecureboot
      - uefi-other-nosecureboot

  connection: ansible.builtin.local
  gather_facts: false
  strategy: host_pinned # free  #allows each cluster to start next task before all clusters have finished current task
  environment:  # if set here - hypercore modules will automatically use this for each remote cluster - avoiding need to specify cluster_instance for each test
    SC_HOST: "https://{{ inventory_hostname }}"
    SC_USERNAME: "{{ scale_user }}"
    SC_PASSWORD: "{{ scale_pass }}"

  tasks:
  - name: Vtpm-other-nosecureboot template - https import if not present # used to clone and cloud-init target VM
    scale_computing.hypercore.vm_import:
      vm_name: "{{ item }}"
      http_uri:
        path: "https://github.com/ddemlow/hc_ovmf_templates/raw/master/{{ item }}/"
        file_name: "{{ item }}.xml"
    retries: 2
    delay: 5
    loop: "{{ image_name }}"

  - name: Protect template from powering on
    scale_computing.hypercore.vm_params:
      vm_name: "{{ item }}"
      tags:
        - template
      vcpu: 0
      power_state: stop
      force_reboot: true
      shutdown_timeout: 10
    loop: "{{ image_name }}"

